pypro/base/urls.py
from django.urls import path

from pypro.base import views

app_name = 'base'
urlpatterns = [
    path('', views.home, name='home'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
    path('modulos/', include('pypro.modulos.urls')),
    path('turmas/', include('pypro.turmas.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/base/models.py
from django.apps import apps
from django.contrib import auth
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name) # noqa
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    def with_perm(self, perm, is_active=True, include_superusers=True, backend=None, obj=None):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    'You have multiple authentication backends configured and '
                    'therefore must provide the `backend` argument.'
                )
        elif not isinstance(backend, str):
            raise TypeError(
                'backend must be a dotted import path string (got %r).'
                % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, 'with_perm'):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = f'{self.first_name}'
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/base/views.py
from django.http import HttpResponse # noqa
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Curso Teste Django{% endblock title %}</title>

    <meta name="description" content="{% block description %}Página do Curso teste Django{% endblock description %}">
    <meta name="author" content="Victor Morais">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'base:home' %}">Curso Django</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Módulos
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for modulo in MODULOS %}
            <li><a class="dropdown-item" href="{{modulo.get_absolute_url}}">{{modulo.titulo}}</a></li>
            <li><hr class="dropdown-divider"></li>
            {% endfor %}
          </ul>
        </li>
      </ul>
      {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.first_name }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
            </div>
          </li>
        </ul>
      {% else %}
      <a href="{% url 'login' %} "class="btn btn-light my-2">Entrar</a>
      {% endif %}
    </div>
  </div>
</nav>

{% block body %}{% endblock body %}

{% include 'base/footer.html' with contato_email="victorsanmorais@gmail.com" only %}

</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
  <div class="container">
	  <div class="row">
		  <div class="col">
			  <h3> Entre em Contato </h3>
			  <address>
				  <a href="5521991604604" class="text-light">+55 21 991-604-604</a>
				  <br/>
				  <a href="mailto:{{contato_email}}" class="text-light">{{contato_email}}</a>
			  </address>
		  </div>
	  </div>
  </div>
  <div class="rights pb-4">
	  <div class="container">
		  <div class="row">
			  <div class="col">
				  {% now 'Y' %} Victor Morais. Todos direitos reservados.
			  </div>
		  </div>
      </div>
  </div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Curso Teste Django - Home{% endblock title %}

{% block body %}

    <div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2>
					Plataforma Teste Django
				</h2>
					<h3 class="mt-4">Para mais informações, assine.</h3>
						<form action="https://testandodjango.us5.list-manage.com/subscribe/post?u=7f88bc1ee19f951c43cb2fd04&amp;id=ba9be30e73"
							  method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
							  class="row gy-2 gx-3 pb-4 align-items-center" target="_blank" novalidate>
						  <div class="row gy-2 gx-3 align-items-center">
							  <div class="col-auto">
								<label class="sr-only" for="mce-EMAIL"></label>
								<input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL"
									   placeholder="exemplo@email.com">
							  </div>
							  <div class="col-auto">
								<label class="sr-only" for="mce-FNAME"></label>
								<input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME"
										placeholder="Seu Nome">
							  </div>
							  <div class="col-auto pt-4">
								<button type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"
										class="btn btn-primary">Assinar</button>
							  </div>
							  <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
							  <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_7f88bc1ee19f951c43cb2fd04_ba9be30e73"
																										tabindex="-1" value=""></div>
						  </div>
						</form>

				<p >
					Este é o projeto usado para treinar a construção de um aplicativo web Django, aplicativo este consistente em uma plataforma de cursos com uma série de features.
					Este site é baseado no projeto desenvolvido no curso <a href="https://plataforma.dev.pro.br">Python Pro</a>
				</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<h5 class="card-header">
					Conteúdo adicional genérico desta plataforma
				</h5>
				<div class="card-body">
					<p class="card-text">
						<img src="{% static 'img/cat.png' %}" alt="Foto de um gato"
							 class="img-thumbnail img-responsive float-start me-3"/>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit.
						Ut imperdiet felis non sollicitudin fringilla.
						Donec aliquam tincidunt dui sed elementum. Proin nec tortor mi.
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare a dui ac tincidunt.
						Sed nec nunc diam. Ut ut scelerisque nisi, et venenatis massa. Suspendisse potenti.
						Praesent feugiat est eu cursus dignissim. Donec varius leo ac est pharetra feugiat non ac purus.
						Quisque urna magna, cursus a elit sed, bibendum blandit arcu.
						Phasellus tincidunt felis sit amet justo venenatis, id ultrices dolor posuere.
						Pellentesque bibendum mattis velit, ac scelerisque lectus fringilla sed.
					</p>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock body %}